name:                hmlc
version:             0.1.0.0
github:              "JKTKops/grape1-programs"
license:             BSD-3-Clause
author:              "Max Kopinsky"
maintainer:          "zerglingk9012@gmail.com"
copyright:           "2025 Max Kopinsky"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hmlc#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.7
- deepseq >= 1.5.0.0
- filepath >= 1.5
- monad-loops >= 0.4.3
- prettyprinter >= 1.7
- text
- transformers >= 0.6

language: GHC2024
default-extensions:
- OverloadedStrings
- DerivingVia

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hmlc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmlc

tests:
  hmlc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmlc
